config/routes.rb
BenchlingChallenge::Application.routes.draw do

  resources :devices do
    resources :messages
  end
 
  root to: "devices#index"
  match 'messages/receive' => "messages#receive"

end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id               :integer          not null, primary key
#  registration_key :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Device < ActiveRecord::Base
  attr_accessible :registration_key
  before_create { |device| device.registration_key = SecureRandom.hex(10) }
  has_many :messages
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  device_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  data       :binary
#

class Message < ActiveRecord::Base
  attr_accessible :device_id, :data
#  has_attached_file :data, :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :path => "/:id/:filename"
  belongs_to :device
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @device = Device.new
    @devices = Device.all
  end

  def create
    @device = Device.create()
    flash[:success] = "Your device key is: #{@device.registration_key} and your device id is: #{@device.id}"
    redirect_to @device
  end

  def show
    @device = Device.find(params[:id])

    #Pull last message and decode the data
    require 'probuff.pb'
    pb = ProBuff::MyMessage.new 
    @message = pb.parse_from_string(@device.messages.last.data).as_json if !@device.messages.last.nil?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    #Find and decode all of the messages
    require 'probuff.pb'
    @messages = []
    Message.where("device_id = #{params[:device_id]}").each do |message_enc|
      msg = ProBuff::MyMessage.new 
      @messages.append(msg.parse_from_string(message_enc.data).as_json)
    end
  end

  def new
    @device_id = params[:device_id]
    @device = Device.find(@device_id)
    @message = @device.messages.build
  end

  def create 
    device_id = (params[:message][:device_id]).to_i
    device = Device.find(device_id)

    if !device.nil?
      #Authenticate the device
      reg_key = params[:message][:registration_key]
      if reg_key != device.registration_key
        flash[ failure: "You have the incorrect registration key" ]
        redirect_to device
        return 
      end

      #Encode the data with ProtoBuf
      require 'probuff.pb'
      data = params[:message][:data]
      msg = ProBuff::MyMessage.new( registration_key: reg_key, device_id: device_id )
      msg.data = [data]
      encoded_data = msg.to_s
      @message = Message.create(device_id: device_id, data: encoded_data )
      redirect_to device
    end
  end

  def receive
    device_id = (params[:device_id]).to_i
    device = Device.find(device_id)

    if !device.nil?
      #Authenticate the device
      reg_key = params[:registration_key]
      if reg_key != device.registration_key
        flash[ failure: "You have the incorrect registration key or device id" ]
        redirect_to device 
        return
      end

      Message.create( device_id: device_id, data: params[:data] )
      redirect_to device
    end
  end

  def show
    enc_message = Message.find(params[:id])

    if !enc_message.nil?
      #Decode the data
      require 'probuff.pb'
      pb = ProBuff::MyMessage.new 
      @message = pb.parse_from_string(enc_message.data).as_json
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/devices/create.html.erb
<h1>Devices#create</h1>
<p>Find me in app/views/devices/create.html.erb</p>

app/views/devices/index.html.erb
<h1>Benchling Backend Coding Challenge</h1>
<%= button_to "Register A New Device", controller: "devices", method: :post %>
<hr><br>
<% @devices.each do |device| %>
  <%= link_to "Device ##{device.id}", device %><br>
<% end %>

app/views/devices/show.html.erb
<h1>Device <%= @device.id %></h1>
<p>Last Message:</p>
<p><%= @message if !@message.nil?%></p>

<p><%= link_to "Add a Message", device_messages_path(@device) + "/new" %></p>
<p><%= link_to "See All Messages", device_messages_path(@device) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BenchlingChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash.each { |message| message } if !flash.empty? %>
<%= yield %>
<hr>
<%= link_to "Take Me Home", root_path %>
</body>
</html>

app/views/messages/build.html.erb
Encoded Message: <%= @message %><br>
Decoded Message: <%= @message2 %>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<% @messages.each do |message| %>
  <p><%= message %></p>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message, url: device_messages_path(@device, @message) do |f| %>

  <%= f.label :data %>:<br>
  <%= f.text_field :data %><br>

  <%= f.hidden_field :device_id, value: @device_id %>
  <%= f.hidden_field :registration_key, value: @device.registration_key %>

  <%= f.submit %>
<% end %>

app/views/messages/receive.html.erb
<h1>Messages#receive</h1>
<p>Find me in app/views/messages/receive.html.erb</p>

app/views/messages/show.html.erb
<h1>Show</h1>
<%= @message.data.url %>